### ISSUE TITLE
Issues in real_time_video.py

### ISSUE THREAD

**Issue by nadiamahzan** [abhijeet3922/FaceEmotion_ID#1]
Hi, i have run the train_emotion_classifier.py data but with shorter data of fer_2013 where i only took 10 datasets for each emotions and each usage. it trains normally but when i try to run the real_time_video.py, it kept on giving this error:

Traceback (most recent call last):
  File "real_time_video.py", line 49, in <module>
    for (i, (emotion, prob)) in enumerate(zip(EMOTIONS, preds)):
NameError: name 'preds' is not defined
[ WARN:1] terminating async callback

Can u help me with this issue? Your help is very much appreciated, thanks.

**Comment by abhijeet3922** [comment]
I remember I faced this error quite a time while i was experimenting. You would need to debug the "preds" variable. Looking at the code, I feel “preds” variable is getting intialized in side “if len(faces) > 0:” code block.
It may be the case that faces are not getting detected in your system and hence the “preds” variable is not initialized which leads to that error.
Let me know if you are able to debug it.

**Comment by abhijeet3922** [comment]
Here is the solution.

https://github.com/omar178/Emotion-recognition/issues/1#issuecomment-485226615
